# A TOML linter such as Tombi can use this schema to validate your config.
# If you encounter any problems, please file an issue at https://github.com/yazi-rs/schemas.

#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_fallback = "alphabetical"
linemode = "permissions"
show_hidden = false
show_symlink = true
scrolloff = 5
mouse_events = ["click", "scroll", "drag"]


[opener]
drawio = [{ run = "drawio %s", orphan = true, desc = "Draw.io", for = "unix" }]

[open]
prepend_rules = [{ url = "*.drawio", use = "drawio" }]
